### PR TITLE
add support for pyDrone hardware (https://github.com/01studio-lab/pyDrone)

### PR DESCRIPTION
**Pull request by thomascatlee**
pyDrone has a ESP32-S3-WROOM core, with MPU6050 QMC5883L and SPL06-001 sensor chips.
QMC5883L and SPL06-001 connected with MPU6050L AUX I2C.

### CODE REVIEW

**Comment by rtlopez** [comment]
@thomascatlee Thanks for your contribution. I have one note, target header file represents generic configuration, and I don't want connect it to any product. Most of these options can be configured through cli, so it would be grate if you to create a document with short description and list of commands to load instead.

**Comment by rtlopez** [comment]
@thomascatlee And last question. Can you confirm that it really works and flies? Blackbox log or video would be nice :)

**Comment by thomascatlee** [comment]
> @thomascatlee And last question. Can you confirm that it really works and flies? Blackbox log or video would be nice :)

I'm an Newbee, I don't have a transmitter, but it works with BetaFlight, and pyDrone itself can fly,  so I think the hardware is OK.



image

**Comment by thomascatlee** [comment]
How to get blackbox log？betaflight UI button shows “save to file（not supported）”， and I clicked it, only got a 224 bytes file.

image

**Comment by thomascatlee** [comment]
> You can grab some logs by setting `set blackbox_mode test` in cli and then run motor for a while in motors tab. If circuit is protected to work with battery and USB, test with connected battery. If not, run only one mottor a llitle. Ensure that Mag and Baro are enabled. I'd like to ensure that readings aren't to noisy, as I have no hardware to test yet.
> 
> If you rollback changes in target file, then branch will be ready to merge, dump looks fine. Thanks.

Yes, the motors are working, so I said that I thought the hardware is OK.

https://github.com/rtlopez/esp-fc/assets/484823/5fe6f1f6-7a2b-43df-80b1-ef6629d49c14


IMG_20240625_112244

**Comment by rtlopez** [comment]
> How to get blackbox log？betaflight UI button shows “save to file（not supported）”， and I clicked it, only got a 224 bytes file.

Yes, it is the only way MSC is not implemented. Keep in mind, that It is important to erase flash area before first use. I've merge your changes to develop branch. There are also other changes there including blackbox improvements, so it would be good to test it one more time using this code base.

**Pull request merged**
