### PR TITLE
add gyro MPU6500

### PR DESCRIPTION
**Pull request by AutoPlantBali**
testing MPU6500 on esp32 and rp2040

esp32 use mpu6500 SPI
esp32_mpu6500_spi

esp32 use mpu6500 I2C
esp32_mpu6500_i2c

rp2040 zero use mpu6500 SPI
rp2040_mpu6500_spi

### CODE REVIEW

**Comment by skimans** [comment]
you i can connect MPU6500 with SPI ?
wirings....

thanks

**Comment by rtlopez** [comment]
Hi @AutoPlantBali 

Thanks for your contribution, As far as I know, MPU6500 anf MPU9250 are the same chips with the same API. My assumption was that MPU9250 will be able to detect it. It shouldn't be issue if cli report it as 9250. But probably I missed to add `0x70` to `testConnection()` method https://github.com/rtlopez/esp-fc/blob/ede2f6db1ee9e623f5784d2374dff87e72258d91/lib/Espfc/src/Device/GyroMPU9250.h#L92 or there are some devices that report diferrent ID that it is mentioned in documentation. Unfortuanatelly I have no such device to test, that's why I placed `?` in device table. 

Nevertheless I think we can still use your code, but please remove changes in platformio.ini first.

**Comment by AutoPlantBali** [comment]
> you i can connect MPU6500 with SPI ? wirings....
> 
> thanks



> you i can connect MPU6500 with SPI ? wirings....
> 
> thanks

this wiring mpu6500 use spi
mpu6500_spi_wiring

**Comment by AutoPlantBali** [comment]
> Hi @AutoPlantBali
> 
> Thanks for your contribution, As far as I know, MPU6500 anf MPU9250 are the same chips with the same API. My assumption was that MPU9250 will be able to detect it. It shouldn't be issue if cli report it as 9250. But probably I missed to add `0x70` to `testConnection()` method
> 
> https://github.com/rtlopez/esp-fc/blob/ede2f6db1ee9e623f5784d2374dff87e72258d91/lib/Espfc/src/Device/GyroMPU9250.h#L92
> 
> or there are some devices that report diferrent ID that it is mentioned in documentation. Unfortuanatelly I have no such device to test, that's why I placed `?` in device table.
> Nevertheless I think we can still use your code, but please remove changes in platformio.ini first.

hi @rtlopez..
Thank you for the advice. I will delete GyroMPU6500.h and merge it into code GyroMPU9250.h

**Comment by AutoPlantBali** [comment]
> Hi @AutoPlantBali
> 
> Thanks for your contribution, As far as I know, MPU6500 anf MPU9250 are the same chips with the same API. My assumption was that MPU9250 will be able to detect it. It shouldn't be issue if cli report it as 9250. But probably I missed to add `0x70` to `testConnection()` method
> 
> https://github.com/rtlopez/esp-fc/blob/ede2f6db1ee9e623f5784d2374dff87e72258d91/lib/Espfc/src/Device/GyroMPU9250.h#L92
> 
> or there are some devices that report diferrent ID that it is mentioned in documentation. Unfortuanatelly I have no such device to test, that's why I placed `?` in device table.
> Nevertheless I think we can still use your code, but please remove changes in platformio.ini first.

if added to this line, is it not a problem that the mpu6500 doesn't have a magnetometer sensor?
https://github.com/rtlopez/esp-fc/blob/ede2f6db1ee9e623f5784d2374dff87e72258d91/lib/Espfc/src/Device/GyroMPU9250.h#L92

**Comment by rtlopez** [comment]
Hi @AutoPlantBali 

> if added to this line, is it not a problem that the mpu6500 doesn't have a magnetometer sensor?

I don't think so, mag communication is implemented in diferrent device class, gyro driver has to only configure internal i2c bus. GY-88 module use this configuration for HMC5338L through MPU-6050 IIRC, so I plan to play with it soon, as mag is not working there now.

**Comment by rtlopez** [comment]
@AutoPlantBali I merged your PR to develop branch now, your changes appear in next release. Thanks for your contribution.

**Pull request merged**
